# Generated by Django 3.2.8 on 2021-10-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user/profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
